version: 1.0.{build}-{branch}

configuration:
- Debug
- Release

platform:
- x86
- x64

install:
- git submodule update --init --recursive

build:
  project: nf4s
  parallel: true
  verbosity: minimal

test_script:
- echo @.\%Platform:x86=%\%Configuration%\testing.exe > test.bat
- test.bat

deploy: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
