version: 1.0.{build}-{branch}

configuration:
- Debug
- Release

platform:
- x86
- x64

install:
- git submodule update --init --recursive
- set

build:
  project: nf4s
  parallel: true
  verbosity: minimal

deploy: off
