version: 1.0.{build}-{branch}

configuration:
- Debug
- Release

platform:
- x86
- x64

install:
- git submodule update --init --recursive

build:
  project: nf4s
  parallel: true
  verbosity: minimal

test_script:
- .\%Platform:x86=%\%Configuration\testing.exe

deploy: off
